name: download-neo4j

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: df check 1
      run: df -h
    - name: Download Neo4j
      run: |
          curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
          echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable 4.1" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
          sudo apt update 
          sudo apt install neo4j 
    - name: df check 2
      run: df -h
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: df check 3
      run: df -h  
    - name: Download OSF files #osf -p 6jtc9 fetch Datasets/Datasets.zip Datasets.zip; unzip Datasets.zip; 
      run: |        
        echo 'Downloading OSF data...';
        osf -p 6jtc9 fetch Datasets/petagraph_v5.zip petagraph_v5.zip;
        unzip petagraph_v5.zip; rm petagraph_v5.zip;
        echo 'Finished Downloading and unzipping....';
        ls data;
    - name: Give permissions
      run: |
          sudo chmod 777 -R /var/lib/neo4j/;
          sudo chmod 777 -R /etc/neo4j;
          sudo chmod 777 -R /var/log/neo4j/;
          sudo chmod 777 -R /var/run/neo4j
    - name: reduce csv sizes
      run: python3 tests/reduce_petagraph_csv_size_github_actions.py
    - name: mv
      run: |
        rm import/CUI-TUIs.csv; rm import/CUI-SUIs.csv; rm import/CODE-SUIs.csv
        mv import/C*.csv  /var/lib/neo4j/import/;
        ls /var/lib/neo4j/import/;
    - name: df check 4
      run: df -h
    - name: Build Petagraph # rm -rf data/databases/*; rm -rf data/transactions/*
      run: |
        rm -rf /var/lib/neo4j/data/databases/*
        rm -rf /var/lib/neo4j/data/transactions/*
        cd /var/lib/neo4j/
        export HEAP_SIZE=1G
        echo heapsize = $HEAP_SIZE
        neo4j-admin import --verbose --nodes=Concept="import/CUIs.csv" --nodes=Code="import/CODEs.csv"   --relationships="import/CUI-CUIs.csv" --relationships=CODE="import/CUI-CODEs.csv"  --skip-bad-relationships --skip-duplicate-nodes
        neo4j start
    

