name: download-neo4j

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Download Neo4j
      run: wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
    - run: echo 'deb https://debian.neo4j.com stable 5' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
    - run: sudo apt-get update
    - run: apt list -a neo4j

