name: download-neo4j

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - run: curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
    - run: echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable 4.1" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
    - run: sudo apt update
    - run: sudo apt install neo4j
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
        echo 'Downloading OSF data...';
        osf -p 6jtc9 fetch Datasets/Datasets.zip Datasets.zip;
        echo 'Finished Download....';
        ls;
        echo 'Unzipping...';
        unzip Datasets.zip;
        echo '--------------------'
        ls PetagraphData
    - name: Test neo4j
      run: ls /bin ; /bin/neo4j
    

