name: download-neo4j

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Download Neo4j
      run: |
          curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
          echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable 4.1" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
          sudo apt update 
          sudo apt install neo4j 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Download OSF files #osf -p 6jtc9 fetch Datasets/Datasets.zip Datasets.zip; unzip Datasets.zip; 
      run: |        
        echo 'Downloading OSF data...';
        osf -p 6jtc9 fetch Datasets/Petagraph_datasets.zip Petagraph_datasets.zip; 
        unzip Petagraph_datasets.zip; rm Petagraph_datasets.zip;
        osf -p 6jtc9 fetch reduced_csvs_github_actions.zip reduced_csvs_github_actions.zip;
        unzip reduced_csvs_github_actions.zip; rm reduced_csvs_github_actions.zip;
        echo 'Finished Downloading and unzipping....';
        ls data;

    - name: Build Petagraph 
      run: |
        sudo chmod 777 -R /var/lib/neo4j/; sudo chmod 777 -R /etc/neo4j;
        sudo chmod 777 -R /var/log/neo4j/; sudo chmod 777 -R /var/run/neo4j
        mv reduced_csvs_github_actions/C*.csv  /var/lib/neo4j/import/;
        rm -rf /var/lib/neo4j/data/databases/*
        rm -rf /var/lib/neo4j/data/transactions/*
        cd /var/lib/neo4j/
        export HEAP_SIZE=1G; echo heapsize set to: $HEAP_SIZE; #  --relationships="import/CUI-CUIs.csv"
        neo4j-admin import --verbose --nodes=Concept="import/CUIs.csv"  --nodes=Code="import/CODEs.csv"    --relationships=CODE="import/CUI-CODEs.csv"  --skip-bad-relationships --skip-duplicate-nodes
        echo 'starting database...'
        #neo4j start

    - name: Run Tests
      run: |
        pwd; ls;
        neo4j-admin set-initial-password 'neo4j2020'
        neo4j start
        python3 tests/Petagraph_ingestion_test_auto.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: QC Report
        path: .github/graph_test_logs/logfile.txt

           
           
           
    
    

